### ISSUE TITLE
Support definition files

### ISSUE THREAD

**Issue by Sythivo** [4teapo/zed-luau#5]
Majority of the definition file would be a single color, compared to VSCode where the syntax highlighting is normal

Zed (zed-luau 0.2.1)
![image](https://github.com/user-attachments/assets/dfe4a573-5c07-4b7b-8f16-5fc530999d19)
VSCode (luau-lsp 1.35.0)
![image](https://github.com/user-attachments/assets/83b3cb6a-0970-464a-a0d3-9f89669a178e)

**Comment by 4teapo** [comment]
zed-luau indeed does nothing to support definition files atm. I'm going to add d.luau as a separate language but still contained in this extension late next month.

**Comment by 4teapo** [comment]
Added in 0.2.2. It turned out to make much more sense to include it in the Luau grammar directly.
